### ISSUE TITLE
Sintel Evaluation Results

### ISSUE THREAD

**Issue by Davidyao99** [Junyi42/monst3r#26]
I am trying to reproduce the evaluation results on Sintel dataset. I followed your scripts and obtained the following results for pose and and depth. For pose, I ran it only on the subset, whereas depth is ran on all sintel videos.

Pose:
ATE: 0.11487, RPE-t: 0.04812, RPE-r: 0.8796

Depth (align_with_lstsq):
Abs Rel: 0.4521, delta < 1.25: 0.6039

Depth (scale):
Abs Rel: 0.3476, delta < 1.25: 0.5497

It seems like the Pose and depth results (scale alignment) is similar to the results that you have in your table. However, the alignment with scale and shift seems to be slightly different I wanted to check that I am using the right parameters in eval depth to reproduce the results.

I am simply calling the depth_evaluation using the following paramters:
```
depth_results, error_map, depth_predict, depth_gt = depth_evaluation(pr_depth, gt_depth, max_depth=70, align_with_lad2=False, use_gpu=True, post_clip_max=70, align_with_lstsq=True)
```

Is this the same setting that you used for the scale + shift alignment? I suppose the alignment might be affected by outliers which lead to different results?

**Comment by Junyi42** [comment]
Hi @Davidyao99,

Thanks for your feedback!

We just updated the evaluation setup for the pose (one minor hyperparameter) and depth evaluation (setup for scale&shift align): https://github.com/Junyi42/monst3r/commit/30d497f6f8635dd06bf9029646850ae765851ae5.

The results I got on another machine are as follows: 

Average ATE: 0.10970, Average RPE trans: 0.04207, Average RPE rot: 0.73328

For the scale&shift alignment, since our method is trained with scale-invariant loss instead of affine-invariant loss. We use "least absolute distance (lat)" instead of the "least square distance (lstsq)" for the optimization. Please refer to [this line](https://github.com/Junyi42/monst3r/blob/30d497f6f8635dd06bf9029646850ae765851ae5/depth_metric.ipynb?short_path=3ca63b1#L74) for the detailed configuration.

Thanks!
