### ISSUE TITLE
Some failed cases

### ISSUE THREAD

**Issue by zhw-zhang** [Junyi42/monst3r#35]
Hi, during testing, I encountered some failed cases.

In Case 1, it seems that the foreground content is too large, causing the model to treat it as static content when estimating the camera parameters.
In Case 2, there appears to be an error in prediction for the middle frames, resulting in a noticeable abrupt change in the camera trajectory. (Among them, case_1-1 and case_2-2 may not be available for online preview; they can be downloaded for viewing.)

Is there any way to assess the accuracy of the final camera parameter estimation or to avoid these types of errors?"

https://github.com/user-attachments/assets/f887d4f7-602f-4b7e-afb5-b6f1bcec16cc

https://github.com/user-attachments/assets/63886832-884f-4b00-9248-cddbbb25edb7

https://github.com/user-attachments/assets/9b56f01f-7c22-4405-9fba-76a8c24cf3c7

https://github.com/user-attachments/assets/e04b2bca-e291-4426-820f-e67df565739b

**Comment by Junyi42** [comment]
Hi @zhw-zhang,

Thanks for the feedback. You can refer to the Sec 4.3 of paper "Structure and Motion from Casual Videos" on using the "Residual Flow Error" as a way to evaluate the depth and camera pose when no ground truth is provided.

To avoid these types of error, one simple way is to increase the [`--translation_weight`](https://github.com/Junyi42/monst3r/blob/main/dust3r/training.py#L114C28-L114C46) argument (e.g., to 10 or 100) to penalize the translation of predicted camera trajectory, since the camera is static.

Best.

**Comment by zhw-zhang** [comment]
Thanks. I wonder if there are any methods to further check or filter out incorrect camera parameters.
