### ISSUE TITLE
How to derive the dynamic & static masks using DUSt3R's code and MONSt3R's weights?

### ISSUE THREAD

**Issue by haodong2000** [Junyi42/monst3r#6]
Hi Junyi,

Thanks for your great work! I am very curious about the dynamic & static segmentation, which can be derived from the predicted flows. And here is a simple check of the `output = inference(pairs, model, device, batch_size=1, verbose=not silent)` in Line152 of `dust3r/dust3r/demo.py`:

```
(Pdb) output.keys()
dict_keys(['view1', 'view2', 'pred1', 'pred2', 'loss'])
(Pdb) output['pred1'].keys()
dict_keys(['pts3d', 'conf'])
```

It seems that I can not get the flows directly, in this case, how can I get the mask for dynamic components?

Thanks,

**Comment by Junyi42** [comment]
Hi @haodong2000,

Thanks for your interest!

Unfortunately, the motion mask is not implemented in DUSt3R's repo. To get the dynamic & static mask, you need to 1) compute the camera intrinsics & relative pose based on the pointmaps prediction (i.e., 'pred1' and 'pred2'); 2) compute the ego flow (or flow due to the camera motion) based on depthmap of the first image and camera intrinsics / relative pose; 3) compute the optical flow based on off-the-self method, e.g., RAFT; 4) compare the ego-flow and RAFT-flow to get the motion mask.

More details can be found in Eq. 1, 2 of our paper (https://monst3r-project.github.io/files/monst3r_paper.pdf), the implementation will be released by next week. Thanks for your patience!

Best
